#
# Makefile for the Linux kernel device drivers.
#
obj-y				+= proxm_class/
obj-n				+= adux-1020/
obj-n				+= cm32180/
obj-y				+= cm36283/
obj-y				+= cm3628/
obj-y				+= al3010/
obj-y				+= proximity/
obj-n                          	+= cap1106/
obj-$(CONFIG_SENSORS_SSC)	+= sensors_ssc.o
